global:
  environment: prod

frontend:
  enabled: true
  namespace: frontend-prod

  replicaCount: 2
  image:
    repository: vyking-frontend
    tag: prod
    pullPolicy: IfNotPresent

  service:
    port: 8080
    targetPort: 80

  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts:
      - host: frontend-prod.local
        paths:
          - path: /
            pathType: Prefix

  hpa:
    enabled: true
    minReplicas: 2
    maxReplicas: 6
    cpuUtilization: 70
    memoryUtilization: 80

backend:
  host: backend-backend.backend-prod.svc.cluster.local
  port: 8081
  enabled: false
