image:
  registry: docker.io
  repository: bitnami/mysql
  tag: 8.0.39-debian-12-r1

auth:
  existingSecret: mysql-dev-secret
  secretKeys:
    rootPassword: mysql-root-password
    username: mysql-username
    password: mysql-password
    database: mysql-database

initdbScriptsConfigMap: mysql-init-sql

primary:
  configuration: |-
    [mysqld]
    default_authentication_plugin=mysql_native_password
    max_connections=1000
    connect_timeout=60
    net_read_timeout=60
    net_write_timeout=60
  persistence:
    enabled: true
    size: 8Gi

backup:
  schedule: "0 */48 * * *"   # every 2 days
  pvc: mysql-backups
  envFromSecret:
    name: mysql-dev-secret

resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: 1000m
    memory: 1024Mi
